'use strict';
const http=require('http'),fs=require('fs'),path=require('path');
const { DatabaseSync }=require('node:sqlite');
const externalPort=Number(process.env.PORT)||3000;
const backendPort=Number(process.env.BACKEND_PORT)||3001;
process.env.PORT=String(backendPort);
require('./ibtech/server/server.js');
const root=path.join(__dirname,'ibtech');
const dbPath=path.join(__dirname,'ibtech/server/ibtech.db');
let localDb=null; try{localDb=new DatabaseSync(dbPath);try{localDb.exec("ALTER TABLE users ADD COLUMN wallet_kobo INTEGER NOT NULL DEFAULT 0")}catch{};try{localDb.exec("ALTER TABLE transactions ADD COLUMN amount_kobo INTEGER")}catch{};try{localDb.exec("ALTER TABLE transactions ADD COLUMN total_kobo INTEGER")}catch{};localDb.exec(`CREATE TABLE IF NOT EXISTS data_plans (id TEXT NOT NULL, network TEXT NOT NULL, label TEXT NOT NULL, price REAL NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, updated_at INTEGER NOT NULL, updated_by TEXT, PRIMARY KEY(id,network))`);localDb.exec("UPDATE users SET wallet_kobo=ROUND(wallet*100) WHERE wallet_kobo=0 AND wallet<>0");const n=localDb.prepare('SELECT COUNT(*) n FROM data_plans').get().n;if(!n){const plans=[['100MB','100MB',100],['200MB','200MB',150],['500MB','500MB',300],['1GB','1GB',500],['2GB','2GB',900],['3GB','3GB',1200],['5GB','5GB',1800],['10GB','10GB',3000],['15GB','15GB',4500],['20GB','20GB',6000]];const ins=localDb.prepare('INSERT INTO data_plans(id,network,label,price,enabled,updated_at) VALUES(?,?,?,?,1,?)');['MTN','GLO','AIRTEL','9MOBILE'].forEach(net=>plans.forEach(p=>ins.run(p[0],net,p[1],p[2],Date.now())))}}catch(e){console.error('Data service DB init:',e.message)}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.xml':'application/xml','.txt':'text/plain'};
function body(req){return new Promise((resolve,reject)=>{const a=[];req.on('data',c=>a.push(c));req.on('end',()=>{try{resolve(a.length?JSON.parse(Buffer.concat(a).toString()):{})}catch{resolve({})}});req.on('error',reject)})}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data))}
function authUser(req){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):'';if(!t||!localDb)return null;const s=localDb.prepare('SELECT user_id FROM sessions WHERE token=?').get(t);return s?localDb.prepare('SELECT * FROM users WHERE id=?').get(s.user_id):null}
function dataPlans(req,res){const rows=localDb.prepare('SELECT id,network,label,price,enabled,updated_at AS updatedAt,updated_by AS updatedBy FROM data_plans ORDER BY rowid').all();json(res,200,{ok:true,networks:['MTN','GLO','AIRTEL','9MOBILE'],plans:rows})}
async function dataPurchase(req,res){const u=authUser(req);if(!u)return json(res,401,{ok:false,error:'Not logged in.'});const b=await body(req);const phone=String(b.phone||'').replace(/\D/g,'');const network=String(b.network||'');const planId=String(b.planId||'');if(!/^\d{10,15}$/.test(phone))return json(res,400,{ok:false,error:'Enter a valid recipient phone number.'});const p=localDb.prepare('SELECT * FROM data_plans WHERE network=? AND id=? AND enabled=1').get(network,planId);if(!p)return json(res,404,{ok:false,error:'That data plan is unavailable.'});const amount=Math.round(Number(p.price)*100);const tx='data_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);localDb.exec('BEGIN IMMEDIATE');try{const row=localDb.prepare('SELECT wallet_kobo,wallet FROM users WHERE id=?').get(u.id);const walletKobo=Number(row?.wallet_kobo ?? Math.round(Number(row?.wallet||0)*100));if(walletKobo<amount){localDb.exec('ROLLBACK');return json(res,402,{ok:false,error:`Insufficient wallet balance. Needs ₦${p.price}, wallet holds ₦${(walletKobo/100).toLocaleString('en-NG')}.`})}const next=walletKobo-amount;localDb.prepare('UPDATE users SET wallet_kobo=?,wallet=? WHERE id=?').run(next,next/100,u.id);const hasLedger=!!localDb.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='wallet_ledger'").get();if(hasLedger)localDb.prepare('INSERT INTO wallet_ledger(id,user_id,kind,delta_kobo,balance_kobo,reference,tx_id,created_at,metadata) VALUES(?,?,?,?,?,?,?,?,?)').run('led_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),u.id,'data-purchase',-amount,next,tx,tx,Date.now(),JSON.stringify({network,planId,phone}));localDb.prepare('INSERT INTO transactions(id,user_id,type,network,amount,total,amount_kobo,total_kobo,reference,status,reason,date) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(tx,u.id,'data-purchase',network,p.price,p.price,amount,amount,tx,'pending',phone,Date.now());localDb.exec('COMMIT');return json(res,200,{ok:true,order:{id:tx,type:'data-purchase',network,planId,label:p.label,phone,amount:p.price,status:'pending',date:Date.now()},wallet:next/100,note:'Data order recorded successfully. Fulfilment is pending the connected service provider.'})}catch(e){try{localDb.exec('ROLLBACK')}catch{};console.error(e);return json(res,500,{ok:false,error:'Could not place the data order.'})}}
async function adminDataPlans(req,res){const u=authUser(req);if(!u||u.role==='user')return json(res,403,{ok:false,error:'Admin access required.'});const b=await body(req);const network=String(b.network||'');const plans=Array.isArray(b.plans)?b.plans:[];if(!['MTN','GLO','AIRTEL','9MOBILE'].includes(network))return json(res,400,{ok:false,error:'Unknown network.'});try{localDb.exec('BEGIN IMMEDIATE');for(const p of plans){localDb.prepare('UPDATE data_plans SET price=?,enabled=?,label=?,updated_at=?,updated_by=? WHERE id=? AND network=?').run(Math.max(0,Number(p.price)||0),p.enabled?1:0,String(p.label||p.id),Date.now(),u.id,String(p.id),network)}localDb.exec('COMMIT');return json(res,200,{ok:true,network,plans:localDb.prepare('SELECT id,network,label,price,enabled,updated_at AS updatedAt,updated_by AS updatedBy FROM data_plans WHERE network=?').all(network)})}catch(e){try{localDb.exec('ROLLBACK')}catch{};return json(res,400,{ok:false,error:e.message})}}
function proxy(req,res){const r=http.request({hostname:'127.0.0.1',port:backendPort,path:req.url,method:req.method,headers:{...req.headers,host:'127.0.0.1:'+backendPort}},br=>{res.writeHead(br.statusCode,br.headers);br.pipe(res)});r.on('error',e=>{res.writeHead(502,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:e.message}))});req.pipe(r)}
function normalizeHtml(html){return html.replace(/Epin Manager/gi,'ePINs').replace(/ePIN Manager/gi,'ePINs').replace(/EPIN MANAGER/gi,'ePINs').replace(/images\/branding\/ib-tech-epins-logo\.webp/g,'images/branding/ib-tech-epins-logo.svg').replace('</nav>','<a href="services.html"><span class="ic">＋</span> Buy Services</a></nav>')}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});if(req.url.startsWith('/api/data-plans')&&req.method==='GET')return dataPlans(req,res);if(req.url.startsWith('/api/data/purchase')&&req.method==='POST')return dataPurchase(req,res);if(req.url.startsWith('/api/admin/data-plans')&&req.method==='POST')return adminDataPlans(req,res);if(req.url.startsWith('/api/'))return proxy(req,res);if(req.method!=='GET'){res.writeHead(405);return res.end('Method Not Allowed')};let u=req.url.split('?')[0];if(u==='/')u='/index.html';const f=path.normalize(path.join(root,u));if(!f.startsWith(root+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);return res.end('Not found')};const ext=path.extname(f).toLowerCase();if(ext==='.html'){const html=normalizeHtml(fs.readFileSync(f,'utf8'));res.writeHead(200,{'Content-Type':mime[ext]});return res.end(html)}res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(res)});server.on('error',e=>{console.error('IB-TECH web gateway error:',e);process.exit(1)});server.listen(externalPort,'0.0.0.0',()=>console.log(`IB-TECH web gateway ready on 0.0.0.0:${externalPort}`));